### ISSUE TITLE
OrdinalCategoricalBucketer number of buckets

### ISSUE THREAD

**Issue by orchardbirds** [ing-bank/skorecard#8]
Everything by default is in 1 bucket, 'Other'
```python
bucketer = OrdinalCategoricalBucketer(max_n_categories=3, variables=['EDUCATION'], encoding_method='ordered')
bucketer.fit_transform(X, y).head()['EDUCATION'].unique()
bucketer.bucket_table('EDUCATION')
```
As opposed to:

```python
bucketer = OrdinalCategoricalBucketer(max_n_categories=3, variables=['EDUCATION'], encoding_method='ordered', tol=0)
bucketer.fit_transform(X, y).head()['EDUCATION'].unique()
bucketer.bucket_table('EDUCATION')
```

**Comment by timvink** [comment]
Indeed, when `encoding_method='ordered'`, things seem fine:

![image](https://user-images.githubusercontent.com/5570380/122101837-0ea10200-ce15-11eb-81de-fa4e168edb58.png)

With `encoding_method='ordered'`, everything ends up in the 'other bucket'

![image](https://user-images.githubusercontent.com/5570380/122102056-4f008000-ce15-11eb-914a-096be23dd70b.png)

Root cause was `sort_values(ascending=True)` should have been `False`.

Fix:

![image](https://user-images.githubusercontent.com/5570380/122102503-c6ceaa80-ce15-11eb-9ce4-5480be148046.png)
